### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by 2bndy5** [nRF24/RF24Ethernet#27]
when abstracting the docs I must've missed this dead link to an example called _SimpleServer_mesh.ino_. Could this be what Getting_Started_SimpleServer_Mesh example is today?

[line with original link before I abstracted docs into MD files](https://github.com/nRF24/RF24Ethernet/blob/ef5b3313ba62e7c48aad04a98bfd0d9d419ed9bd/RF24Ethernet.h#L463)

**Comment by TMRh20** [comment]
Yeah, looks like that’s the one.
