### ISSUE TITLE
Main URL in client examples is no longer valid

### ISSUE THREAD

**Issue by TMRh20** [nRF24/RF24Ethernet#43]
Reminder to update client examples with a new URL since http://fiikus.net/asciiart/pizza.txt is no longer valid. 
Hard to find links to good ascii art that don't use SSL...

**Comment by 2bndy5** [comment]
Yeah, SSL is pretty much standard nowadays. Firefox actually tries to prevent me from visiting sites that don't use https.

What about ftp?

**Comment by TMRh20** [comment]
Using FTP might require some slight changes to the code, but should work as a good alternative.

**Comment by TMRh20** [comment]
Found an unsecure site with a bunch of ASCII art etc:  http://artscene.textfiles.com/asciiart/texthistory.txt

I think we can use this.

**Comment by TMRh20** [comment]
Now it seems the secondary URL is down as well lol. But I also found http://mewbies.com/geek_fun_files/scarecrow_ascii_art_archive/19941205_ASCII%20Art%20Resources.htm

**Comment by 2bndy5** [comment]
On my android, firefox automatically replaces the URL's http with https. Obviously, https does not work.

**Comment by TMRh20** [comment]
Interesting, that's probably best-practice nowadays. There's probably a setting to allow non-secure sites you would think. 
Looks like the backup URL is back up now too [here](http://109.120.203.163/web/blyad.club/library/litrature/Salvatore,%20R.A/Salvatore,%20R.A%20-%20Icewind%20Dale%20Trilogy%201%20-%20Crystal%20Shard,%20The.txt)
