### ISSUE TITLE
TCP/IP via two ESP32 devices

### ISSUE THREAD

**Issue by epsi1on** [nRF24/RF24Ethernet#50]
Hi,

Please consider this topology:
![image](https://github.com/user-attachments/assets/17ab8758-7889-4427-97a3-e08122dd43f5)
Think of device 1 want to ping device 2 with Linux `ping` command. I would be thankful if you give me some guidance.
I would like to know if it is possible to make NRF24L01, transparent for communication so that two devices can directly communicate via TCP or UDP. if not, how can i get a tcp or udp stream between two ESP32 Wroom devices? I'm not limited to ESP32 so can use other micro controllers as well.
My main idea is to use LanChat apps on two android devices to have voice call through NRFs where two devices are not possible to directly connect with wifi (like they are far away from each other). As devices could use compression for sound, i think maybe 250kbps is even more than enough for those.
Thanks for great work

**Comment by 2bndy5** [comment]
I believe [RF24Gateway](https://github.com/nRF24/RF24Gateway) is the sister library to RF24Ethernet but for Linux. Unfortunately, we don't have a python binding on Linux for RF24Gateway.

**Comment by epsi1on** [comment]
Thanks for reply.
I actually mean something like the [nerfnet](https://github.com/aarossig/nrfnet) which two raspberry pi clients can communicate via TCP/IP together via NRF medium. each one have an IP and could ping each other with ping command in linux.
I mean such level of integrity into linux device, not a simply python binding. It is actually a little hard for me to understand wether RF24Gateway or RF24Ethernet could be used for that purpose.

**Comment by TMRh20** [comment]
Yes, that is basically what RF24Gateway does, it uses the nRF24 radio as a standard NIC.

This allows users to utilize virtually any standard protocol that works over TCP/IP or UDP, without needing to do any specific coding etc. Just set up the devices with RF24Gateway and it works like a standard network card.

**Comment by epsi1on** [comment]
Kindly thank you
