### ISSUE TITLE
Arduino SLIP Gateway - Http Server problems

### ISSUE THREAD

**Issue by catan85** [nRF24/RF24Ethernet#8]
As I writed on the RF24Mesh lib I'm experiencing some problems on the samples SLIP Gateway and Http Server. When the SLIP Gateway is turned off, then I have to turn off and turn on the Http Server to reestabilish the connection. Is there a work around?
The only modification I apported to the sample is the ce and csn pins (I use 9,10).
Only a question, If I remove the gateway and use directly the raspberry, would it be more reliable or it is the same? Now I've some problem using directly the raspberry but, if you tell me that it will work better then I will work on it..

**Comment by TMRh20** [comment]
> When the SLIP Gateway is turned off, then I have to turn off and turn on the Http Server to reestabilish the connection. Is there a work around?

I assume that the USB->SLIP interface is being affected. I assume you could use a board like Pro Mini which uses a separate FTDI cable, and the serial connection will stay active when the board is turned off etc.

> Only a question, If I remove the gateway and use directly the raspberry, would it be more reliable or it is the same?

RPi is better & uses improved code vs micro-controllers.
